### ISSUE TITLE
Clarification on #142

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/perfil-politico#160]
PR #142 is a bit awkward to me. The description has no context or purpose for the changes, which break the tests:

* The description says it's a documentation related PR, but it actually changed code too
* Test expects the [redirect](https://github.com/okfn-brasil/perfil-politico/blob/c53e15c09a3a9b9cd07bbd5550a4022913d755fe/perfil/core/tests/test_home_view.py#L6-L7) removed in the code edits from the PR
* The [new code does not follow Black style](https://travis-ci.org/github/okfn-brasil/perfil-politico/jobs/773176106#L549)

Surely I can fix that, but before I would like to know more about the context of these changes.

My point is: as tests weren't updated, code edits were not mentioned or justified, and no one in the PR discussion seemed to worry about the CI being red I am not sure if this new state is intentional. Therefore I don't know the direction the fix should go:

* Should the tests be updated to match the code state after the PR being merged? 
* Or should the code edited in the PR be reverted (keeping only the docs update)?

cc people involved in that PR @adorilson @dehatanes @BrunaNayara @julianyraiol @sergiomario 
also cc @giuliocc

**Comment by adorilson** [comment]
Hi, @cuducos .

The purpose was just to update the README to make easier e clearer the setup process. The only code change was made because we understanding it was in this context too. All changes was intended.

We only done the manual test, and it worked.
The test was not updated just for my fail. They must updated, too.

Thanks for review and fixes in #161 . They was really need.

**Comment by cuducos** [comment]
All good then 🎉 
Great teamwork 💜
